// Model and provider constant data
import type { Model, ModelProvider, ProviderInfo } from '@/ai/ai-model';

export const PROVIDERS: Record<ModelProvider, ProviderInfo> = {
  scira: { id: 'scira', name: 'Scira', icon: 'scira' },
  xai: { id: 'xai', name: 'xAI', icon: 'xai', hasNew: true },
  openai: { id: 'openai', name: 'OpenAI', icon: 'openai', hasNew: true },
  anthropic: { id: 'anthropic', name: 'Anthropic', icon: 'anthropic', hasNew: true },
  google: { id: 'google', name: 'Google', icon: 'google', hasNew: true },
  alibaba: { id: 'alibaba', name: 'Alibaba', icon: 'alibaba', hasNew: true },
  zhipu: { id: 'zhipu', name: 'Zhipu AI', icon: 'zhipu' },
  minimax: { id: 'minimax', name: 'Minimax', icon: 'minimax', hasNew: true },
  deepseek: { id: 'deepseek', name: 'DeepSeek', icon: 'deepseek' },
  moonshot: { id: 'moonshot', name: 'MoonShot', icon: 'moonshot' },
  cohere: { id: 'cohere', name: 'Cohere', icon: 'cohere' },
  bytedance: { id: 'bytedance', name: 'ByteDance', icon: 'bytedance', hasNew: true },
  mistral: { id: 'mistral', name: 'Mistral', icon: 'mistral', hasNew: true },
  arcee: { id: 'arcee', name: 'Arcee', icon: 'arcee' },
  vercel: { id: 'vercel', name: 'Vercel', icon: 'vercel' },
  amazon: { id: 'amazon', name: 'Amazon', icon: 'amazon' },
  xiaomi: { id: 'xiaomi', name: 'Xiaomi', icon: 'xiaomi' },
  kwaipilot: { id: 'kwaipilot', name: 'Kwaipilot', icon: 'kwaipilot' },
  stepfun: { id: 'stepfun', name: 'StepFun', icon: 'stepfun' },
  sarvam: { id: 'sarvam', name: 'Sarvam', icon: 'sarvam', hasNew: true },
  inception: { id: 'inception', name: 'Inception', icon: 'inception', hasNew: true },
  nvidia: { id: 'nvidia', name: 'NVIDIA', icon: 'nvidia', hasNew: true },
};

export const models: Model[] = [
  {
    value: 'scira-auto',
    label: 'Auto',
    description: 'Automatically routes your query to the best model',
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'scira',
  },
  // Models (xAI)
  {
    value: 'scira-grok-3-mini',
    label: 'Grok 3 Mini',
    description: "xAI's recent smallest LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    provider: 'xai',
  },
  {
    value: 'scira-grok-3',
    label: 'Grok 3',
    description: "xAI's recent smartest LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    provider: 'xai',
  },
  {
    // grok-4.20-multi-agent-beta-latest
    value: 'grok-4.20-multi-agent-beta-latest',
    label: 'Grok 4.20 Multi Agent Beta',
    description: "xAI's experimental beta multi-agent model",
    vision: true,
    reasoning: true,
    experimental: true,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    isNew: true,
    provider: 'xai',
  },
  {
    value: 'scira-grok-4',
    label: 'Grok 4',
    description: "xAI's most intelligent LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    provider: 'xai',
  },
  {
    value: 'scira-grok-4.20-experimental-beta-0304',
    label: 'Grok 4.20 Beta',
    description: "xAI's experimental beta chat model",
    vision: true,
    reasoning: false,
    experimental: true,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    isNew: true,
    provider: 'xai',
  },
  {
    value: 'scira-grok-4.20-experimental-beta-0304-thinking',
    label: 'Grok 4.20 Beta Thinking',
    description: "xAI's experimental beta reasoning model",
    vision: true,
    reasoning: true,
    experimental: true,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    isNew: true,
    provider: 'xai',
  },
  {
    value: 'scira-default',
    label: 'Grok 4.1 Fast',
    description: "xAI's greatest and fastest multimodel LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
    provider: 'xai',
  },
  {
    value: 'scira-sarvam-105b',
    label: 'Sarvam 105B',
    description: "Sarvam's flagship model for chat and reasoning",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'sarvam',
    parameters: {
      temperature: 0.5,
    },
  },
  {
    value: 'scira-grok4.1-fast-thinking',
    label: 'Grok 4.1 Fast Thinking',
    description: "xAI's greatest and fastest multimodel reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: true,
    provider: 'xai',
  },
  {
    value: 'scira-grok-4-fast',
    label: 'Grok 4 Fast',
    description: "xAI's previous fastest multimodel LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: false,
    provider: 'xai',
  },
  {
    value: 'scira-grok-4-fast-think',
    label: 'Grok 4 Fast Thinking',
    description: "xAI's previous fastest multimodel reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 30000,
    extreme: true,
    fast: true,
    isNew: false,
    parameters: {
      maxOutputTokens: 30000,
    },
    provider: 'xai',
  },
  {
    value: 'scira-code',
    label: 'Grok Code',
    description: "xAI's advanced coding LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    provider: 'xai',
  },
  {
    value: 'scira-seed-2.0-mini',
    label: 'Seed 2.0 Mini',
    description: "ByteDance's compact and efficient reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    fast: true,
    provider: 'bytedance',
  },
  {
    value: 'scira-seed-2.0-lite',
    label: 'Seed 2.0 Lite',
    description: "ByteDance's lightweight vision model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    fast: true,
    provider: 'bytedance',
  },
  {
    value: 'scira-seed-1.6',
    label: 'Seed 1.6',
    description: "ByteDance's recent reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'bytedance',
  },
  {
    value: 'scira-seed-1.8',
    label: 'Seed 1.8',
    description: "ByteDance's latest reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'bytedance',
  },
  {
    value: 'scira-seed-1.6-flash',
    label: 'Seed 1.6 Flash',
    description: "ByteDance's fast vision reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    fast: true,
    provider: 'bytedance',
  },
  {
    value: 'scira-qwen-32b',
    label: 'Qwen 3 32B',
    description: "Alibaba's base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 40960,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-32b-thinking',
    label: 'Qwen 3 32B Thinking',
    description: "Alibaba's base reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 40960,
    fast: true,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      topK: 20,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-nemotron-3-super',
    label: 'Nemotron 3 Super',
    description: "NVIDIA's powerful Nemotron 3 model",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    provider: 'nvidia',
  },
  {
    value: 'scira-qwen-4b',
    label: 'Qwen 3 4B',
    description: "Alibaba's small base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    maxOutputTokens: 16000,
    freeUnlimited: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-4b-thinking',
    label: 'Qwen 3 4B Thinking',
    description: "Alibaba's small base LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    maxOutputTokens: 16000,
    freeUnlimited: false,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      topK: 20,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-gpt-oss-20',
    label: 'GPT OSS 20B',
    description: "OpenAI's small OSS LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt5-nano',
    label: 'GPT 5 Nano',
    description: "OpenAI's smallest flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
    provider: 'openai',
  },
  {
    value: 'scira-google-lite',
    label: 'Gemini 2.5 Flash Lite',
    description: "Google's advanced small LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    extreme: true,
    isNew: false,
    provider: 'google',
  },
  {
    value: 'scira-ministral-3b',
    label: 'Ministral 3 3B',
    description: "Mistral's mini-model 3B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-ministral-8b',
    label: 'Ministral 3 8B',
    description: "Mistral's mini-model 8B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-devstral',
    label: 'Devstral 2',
    description: "Mistral's coding-focused LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-devstral-small',
    label: 'Devstral Small 2',
    description: "Mistral's small coding-focused LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-ministral-14b',
    label: 'Ministral 3 14B',
    description: "Mistral's mini-model 14B multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-mistral-large',
    label: 'Mistral Large 3',
    description: "Mistral's latest and greatest large multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-mistral-medium',
    label: 'Mistral Medium',
    description: "Mistral's medium multi-modal LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'mistral',
  },
  {
    value: 'scira-magistral-small',
    label: 'Magistral Small',
    description: "Mistral's small reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'mistral',
  },
  {
    value: 'scira-magistral-medium',
    label: 'Magistral Medium',
    description: "Mistral's medium reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'mistral',
  },
  {
    value: 'scira-mistral-small',
    label: 'Mistral Small 4',
    description: "Mistral's small efficient model",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-mistral-small-think',
    label: 'Mistral Small 4 Thinking',
    description: "Mistral's small model with reasoning mode enabled",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-leanstral',
    label: 'Leanstral',
    description: "Mistral's lean and efficient small model",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'mistral',
  },
  {
    value: 'scira-trinity-mini',
    label: 'Trinity Mini',
    description: "Arcee's small reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    parameters: {
      temperature: 0.15,
      topK: 50,
      topP: 0.75,
      minP: 0.06,
    },
    provider: 'arcee',
  },
  {
    value: 'scira-trinity-large',
    label: 'Trinity Large',
    description: "Arcee's large reasoning LLM via OpenRouter",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 0.15,
      topK: 50,
      topP: 0.75,
      minP: 0.06,
    },
    provider: 'arcee',
  },
  {
    value: 'scira-gpt-oss-120',
    label: 'GPT OSS 120B',
    description: "OpenAI's advanced OSS LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-4.1-nano',
    label: 'GPT 4.1 Nano',
    description: "OpenAI's smallest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-4.1-mini',
    label: 'GPT 4.1 Mini',
    description: "OpenAI's small LLM",
    vision: true,
    reasoning: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    extreme: true,
    experimental: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-4.1',
    label: 'GPT 4.1',
    description: "OpenAI's LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.1',
    label: 'GPT 5.1 Instant',
    description: "OpenAI's fast and smart LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.1-thinking',
    label: 'GPT 5.1 Thinking',
    description: "OpenAI's recent and smart reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.2',
    label: 'GPT 5.2 Instant',
    description: "OpenAI's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.3-chat-latest',
    label: 'GPT 5.3 Instant',
    description: "OpenAI's latest chat-optimized LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.4',
    label: 'GPT 5.4 Instant',
    description: "OpenAI's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.4-mini',
    label: 'GPT 5.4 Mini',
    description: "OpenAI's small GPT 5.4 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.4-nano',
    label: 'GPT 5.4 Nano',
    description: "OpenAI's smallest GPT 5.4 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: true,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.4-thinking',
    label: 'GPT 5.4 Thinking',
    description: "OpenAI's latest and greatest reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.4-thinking-xhigh',
    label: 'GPT 5.4 Thinking XHigh',
    description: "OpenAI's latest and greatest reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.2-thinking',
    label: 'GPT 5.2 Thinking',
    description: "OpenAI's latest and greatest reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.2-thinking-xhigh',
    label: 'GPT 5.2 Thinking XHigh',
    description: "OpenAI's latest and greatest reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt5-mini',
    label: 'GPT 5 Mini',
    description: "OpenAI's small flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt5',
    label: 'GPT 5',
    description: "OpenAI's flagship LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-o4-mini',
    label: 'o4 mini',
    description: "OpenAI's recent mini reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-o3',
    label: 'o3',
    description: "OpenAI's advanced LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt5-medium',
    label: 'GPT 5 Medium',
    description: "OpenAI's latest flagship reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.1-codex',
    label: 'GPT 5.1 Codex',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.1-codex-mini',
    label: 'GPT 5.1 Codex Mini',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.1-codex-max',
    label: 'GPT 5.1 Codex Max',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.2-codex',
    label: 'GPT 5.2 Codex',
    description: "OpenAI's latest advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-gpt-5.3-codex',
    label: 'GPT 5.3 Codex',
    description: "OpenAI's latest advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: true,
    provider: 'openai',
  },
  {
    value: 'scira-gpt5-codex',
    label: 'GPT 5 Codex',
    description: "OpenAI's advanced coding LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    extreme: true,
    fast: false,
    isNew: false,
    provider: 'openai',
  },
  {
    value: 'scira-cmd-a',
    label: 'Command A',
    description: "Cohere's advanced command LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'cohere',
  },
  {
    value: 'scira-cmd-a-think',
    label: 'Command A Thinking',
    description: "Cohere's advanced command LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'cohere',
  },
  {
    value: 'scira-kat-coder',
    label: 'KAT-Coder-Pro V1',
    description: "Kwaipilot's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'kwaipilot',
  },
  {
    value: 'scira-deepseek-v3',
    label: 'DeepSeek v3',
    description: "DeepSeek's previous advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-v3.1-terminus',
    label: 'DeepSeek v3.1 Terminus',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-chat',
    label: 'DeepSeek v3.2',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
    },
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-chat-think',
    label: 'DeepSeek v3.2 Thinking',
    description: "DeepSeek's advanced chat LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-chat-exp',
    label: 'DeepSeek v3.2 Exp',
    description: "DeepSeek's advanced chat LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-chat-think-exp',
    label: 'DeepSeek v3.2 Exp Thinking',
    description: "DeepSeek's advanced chat LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-r1',
    label: 'DeepSeek R1',
    description: "DeepSeek's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'deepseek',
  },
  {
    value: 'scira-deepseek-r1-0528',
    label: 'DeepSeek R1 0528',
    description: "DeepSeek's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: false,
    provider: 'deepseek',
  },
  {
    value: 'scira-qwen-coder-small',
    label: 'Qwen 3 Coder 30B A3B Instruct',
    description: "Alibaba's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-coder',
    label: 'Qwen 3 Coder',
    description: "Alibaba's advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-coder-plus',
    label: 'Qwen 3 Coder Plus',
    description: "Alibaba's extremely advanced coding LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5',
    label: 'Qwen 3.5 397B A17B',
    description: "Alibaba's latest flagship LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
    isNew: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
      presencePenalty: 1.5,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5-plus',
    label: 'Qwen 3.5 Plus',
    description: "Alibaba's latest flagship LLM with vision and reasoning",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5-27b',
    label: 'Qwen 3.5 27B',
    description: "Alibaba's Qwen 3.5 27B vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5-35b',
    label: 'Qwen 3.5 35B A3B',
    description: "Alibaba's Qwen 3.5 35B A3B vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: true,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5-122b',
    label: 'Qwen 3.5 122B A10B',
    description: "Alibaba's Qwen 3.5 122B A10B vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    fast: false,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3.5-flash',
    label: 'Qwen 3.5 Flash',
    description: "Alibaba's fast vision reasoning LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    isNew: true,
    provider: 'alibaba',
    parameters: {
      temperature: 1,
      topP: 0.95,
      topK: 20,
      minP: 0,
      presencePenalty: 1.5,
    },
  },
  {
    value: 'scira-qwen-coder-next',
    label: 'Qwen 3 Coder Next',
    description: "Alibaba's next-gen coding LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: false,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-vl-30b',
    label: 'Qwen 3 VL 30B',
    description: "Alibaba's advanced vision LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-vl-30b-thinking',
    label: 'Qwen 3 VL 30B Thinking',
    description: "Alibaba's advanced vision LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    fast: true,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      topK: 20,
      minP: 0,
    },
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-next',
    label: 'Qwen 3 Next 80B A3B Instruct',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    fast: true,
    isNew: false,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-next-think',
    label: 'Qwen 3 Next 80B A3B Thinking',
    description: "Qwen's advanced thinking LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    isNew: false,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-max',
    label: 'Qwen 3 Max',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-max-preview',
    label: 'Qwen 3 Max Preview',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-max-preview-thinking',
    label: 'Qwen 3 Max Thinking',
    description: "Qwen's most advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-235',
    label: 'Qwen 3 235B A22B',
    description: "Qwen's advanced instruct LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.7,
      topP: 0.8,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-235-think',
    label: 'Qwen 3 235B A22B Thinking',
    description: "Qwen's advanced thinking LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 100000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-vl',
    label: 'Qwen 3 VL',
    description: "Qwen's advanced vision LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-qwen-3-vl-thinking',
    label: 'Qwen 3 VL Thinking',
    description: "Qwen's advanced vision LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
      minP: 0,
    },
    isNew: false,
    provider: 'alibaba',
  },
  {
    value: 'scira-kimi-k2.5',
    label: 'Kimi K2.5',
    description: "MoonShot AI's latest vision-enabled LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'moonshot',
  },
  {
    value: 'scira-kimi-k2.5-thinking',
    label: 'Kimi K2.5 Thinking',
    description: "MoonShot AI's latest multi-modal LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'moonshot',
  },
  {
    value: 'scira-kimi-k2-v2',
    label: 'Kimi K2 0905',
    description: "MoonShot AI's advanced base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    parameters: {
      temperature: 0.6,
    },
    provider: 'moonshot',
  },
  {
    value: 'scira-kimi-k2-v2-thinking',
    label: 'Kimi K2 Thinking',
    description: "MoonShot AI's advanced base LLM with thinking",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    parameters: {
      temperature: 1,
    },
    isNew: false,
    provider: 'moonshot',
  },
  {
    value: 'scira-minimax',
    label: 'Minimax M1 80K',
    description: "Minimax's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    parameters: {
      temperature: 0.6,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-minimax-m2',
    label: 'Minimax M2',
    description: "Minimax's advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-minimax-m2.1',
    label: 'Minimax M2.1',
    description: "Minimax's latest advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-minimax-m2.1-lightning',
    label: 'Minimax M2.1 Lightning',
    description: "Minimax's fast advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    fast: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-minimax-m2.7',
    label: 'MiniMax M2.7',
    description: "MiniMax's latest high-speed reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    fast: true,
    isNew: true,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-minimax-m2.5',
    label: 'Minimax M2.5',
    description: "Minimax's most capable reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 10000,
    isNew: false,
    parameters: {
      temperature: 1.0,
      topP: 0.95,
      topK: 40,
    },
    provider: 'minimax',
  },
  {
    value: 'scira-glm-4.6',
    label: 'GLM 4.6',
    description: "Zhipu AI's advanced reasoning LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: false,
    fast: true,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-4.6v-flash',
    label: 'GLM 4.6V Flash',
    description: "Zhipu AI's fast vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: false,
    fast: true,
    parameters: {
      temperature: 0.8,
      topP: 0.6,
      topK: 2,
      frequencyPenalty: 1.1,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-4.6v',
    label: 'GLM 4.6V',
    description: "Zhipu AI's advanced vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: false,
    parameters: {
      temperature: 0.8,
      topP: 0.6,
      topK: 2,
      frequencyPenalty: 1.1,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-4.7',
    label: 'GLM 4.7',
    description: "Zhipu AI's latest advanced reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: false,
    fast: true,
    parameters: {
      temperature: 1,
      topP: 0.95,
    },
  },
  {
    value: 'scira-glm-4.7-flash',
    label: 'GLM 4.7 Flash',
    description: "Zhipu AI's latest fast vision reasoning LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: false,
    fast: true,
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-5',
    label: 'GLM 5',
    description: "Zhipu AI's most powerful LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    parameters: {
      temperature: 1,
      topP: 0.95,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-5-thinking',
    label: 'GLM 5 Thinking',
    description: "Zhipu AI's most powerful reasoning LLM",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 20000,
    isNew: true,
    parameters: {
      temperature: 1,
      topP: 0.95,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm-air',
    label: 'GLM 4.5 Air',
    description: "Zhipu AI's efficient base LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 130000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-glm',
    label: 'GLM 4.5',
    description: "Zhipu AI's previous advanced LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 13000,
    parameters: {
      temperature: 0.6,
      topP: 0.95,
    },
    provider: 'zhipu',
  },
  {
    value: 'scira-google',
    label: 'Gemini 2.5 Flash',
    description: "Google's advanced small LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'google',
  },
  {
    value: 'scira-google-think',
    label: 'Gemini 2.5 Flash Thinking',
    description: "Google's advanced small LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'google',
  },
  {
    value: 'scira-google-pro',
    label: 'Gemini 2.5 Pro',
    description: "Google's advanced LLM",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'google',
  },
  {
    value: 'scira-google-pro-think',
    label: 'Gemini 2.5 Pro Thinking',
    description: "Google's advanced LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: false,
    provider: 'google',
  },
  {
    value: 'scira-gemini-3-flash',
    label: 'Gemini 3 Flash',
    description: "Google's latest small SOTA LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'google',
  },
  {
    value: 'scira-gemini-3-flash-think',
    label: 'Gemini 3 Flash Thinking',
    description: "Google's latest small SOTA LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'google',
  },
  {
    value: 'scira-gemini-3.1-flash-lite',
    label: 'Gemini 3.1 Flash Lite',
    description: "Google's newest lightweight flash LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: true,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    fast: true,
    isNew: true,
    provider: 'google',
  },
  {
    value: 'scira-gemini-3.1-flash-lite-think',
    label: 'Gemini 3.1 Flash Lite Thinking',
    description: "Google's newest lightweight flash LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    fast: true,
    isNew: true,
    provider: 'google',
  },
  {
    value: 'scira-gemini-3.1-pro',
    label: 'Gemini 3.1 Pro',
    description: "Google's newest SOTA LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    extreme: true,
    maxOutputTokens: 10000,
    isNew: true,
    provider: 'google',
  },
  {
    value: 'scira-anthropic-small',
    label: 'Claude Haiku 4.5',
    description: "Anthropic's fast and efficient LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
    max: false,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic',
    label: 'Claude Sonnet 4.5',
    description: "Anthropic's latest and greatest LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-think',
    label: 'Claude Sonnet 4.5 Thinking',
    description: "Anthropic's latest and greatest LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-sonnet-4.6',
    label: 'Claude Sonnet 4.6',
    description: "Anthropic's latest Sonnet LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-sonnet-4.6-think',
    label: 'Claude Sonnet 4.6 Thinking',
    description: "Anthropic's latest Sonnet LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-opus',
    label: 'Claude 4.5 Opus',
    description: "Anthropic's previous advanced LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-opus-think',
    label: 'Claude 4.5 Opus Thinking',
    description: "Anthropic's previous advanced LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: false,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-opus-4.6',
    label: 'Claude 4.6 Opus',
    description: "Anthropic's most advanced LLM",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
    provider: 'anthropic',
  },
  {
    value: 'scira-anthropic-opus-4.6-think',
    label: 'Claude 4.6 Opus Thinking',
    description: "Anthropic's most advanced LLM with thinking",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Max',
    pdf: true,
    pro: true,
    max: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    isNew: true,
    provider: 'anthropic',
  },
  {
    value: 'scira-mimo-v2-flash',
    label: 'Mimo V2 Flash',
    description: "Xiaomi's fast Mimo V2 Flash model via OpenRouter (thinking disabled)",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'xiaomi',
  },
  {
    value: 'scira-mimo-v2-pro',
    label: 'Mimo V2 Pro',
    description: "Xiaomi's advanced Mimo V2 Pro model",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'xiaomi',
  },
  {
    value: 'scira-nova-2-lite',
    label: 'Nova 2 Lite',
    description: "Amazon's latest and smallest LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'amazon',
  },
  {
    value: 'scira-v0-10',
    label: 'Vercel v0 1.0',
    description: "Vercel's v0 1.0 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'vercel',
  },
  {
    value: 'scira-v0-15',
    label: 'Vercel v0 1.5',
    description: "Vercel's v0 1.5 model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 16000,
    isNew: true,
    provider: 'vercel',
  },
  {
    value: 'scira-step-3.5-flash',
    label: 'Step 3.5 Flash',
    description: "StepFun's fast and efficient LLM",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Free',
    pdf: false,
    pro: false,
    requiresAuth: false,
    freeUnlimited: false,
    maxOutputTokens: 8000,
    fast: true,
    isNew: true,
    provider: 'stepfun',
  },
  {
    value: 'scira-mercury-2',
    label: 'Mercury 2',
    description: "Inception's diffusion-based language model",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
    requiresAuth: true,
    freeUnlimited: false,
    maxOutputTokens: 1000,
    fast: true,
    isNew: true,
    provider: 'inception',
  },
];
